print("Thirty" + " Days" + " Of" + "Python")
company = "Coding" + " For" + " All"
print(company)
print(len(company))
print(company.upper())
print(company.lower())
print(company.capitalize(), company.title(), company.swapcase())
print(company[0])
print(bool("Coding" in company))
print(company.replace("Python", "Coding"))
print(company.replace("All", "Everyone"))
print(company.split())
comp_names =  "Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon"
print(comp_names.split(", "))
company = "Coding" + " For" + " All"
print(company[0])
print(company[:-1])
print(company[10])
print(company.index("C"))
print(company.index("F"))
print(company.rfind("l"))
sentence = "You cannot end a sentence with because because because is a conjunction"
print(sentence.find("because"))
print(sentence.rindex("because"))
str_list = sentence.split("because because because")
print("".join(str_list))
print(company.startswith("Coding"))
print(company.startswith("coding"))
print(" Coding For All   ".strip(" "))
print("30DaysOfPython".isidentifier())
print("thirty_days_of_python".isidentifier())
str_list_two = ['Django', 'Flask', 'Bottle', 'Pyramid', 'Falcon']
print("# ".join(str_list_two))
print("I am enjoying this challenge. \n I just wonder what's next.")
print("Name \t Age \t Country \t City \t \n Rafae \t 26 \t Seattle \t US")
a = 8
b = 6
print(f'{a} + {b} = {a +b}')
print(f'{a} - {b} = {a - b}')
print(f'{a} * {b} = {a * b}')
print(f'{a} / {b} = {a / b:.2f}')
print(f'{a} % {b} = {a % b}')
print(f'{a} // {b} = {a // b}')
print(f'{a} ** {b} = {a ** b}')